name: Update README every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update README
        run: |
          # Get the current date and time in desired format
          current_date=$(date +"%Y-%m-%d %H:%M:%S")

          # Append the date and time to the README file
          echo "Last updated: $current_date" >> README.md

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: README.md
          message: "Update README with current date and time"
          committer: GitHub Actions <actions@github.com>
          author: GitHub Actions <actions@github.com>
          branch: main
